Adding Carbon Monoxide Detector input
ebaauw/homebridge-rpi pull request #150
Opened 2022-11-26 04:24 UTC by wjsroot

I know you do this voluntarily. I'm trying not to make more work for you. I'd like to have a GPIO input tied to a carbon monoxide detector. I've forked your code, made the changes that I believe are needed (based on other devices which register as CO detectors) but I've failed at getting the code into a state where I can test it. My Node and Git skills are practically nonexistent. If possible, please disregard the second commit.
Please let me know if there's anything I should be doing differently or anything I can do to help. Thanks for making it this far.

2022-11-26 08:58 UTC, ebaauw requested changes
Thanks for the PR.  Always nice to see others taking my software a step further!

For testing during development, I create a symlink in `/usr/lib/node_modules` (or `/usr/local/lib/node_modules`, depending on your NodeJS installation) to the `homebridge-rpi`directory.  Make sure to run `npm i` in that directory to install the dependencies, and you should be good to go.  Only for testing on a separate server, I release a beta version through `npm`.

I think you understand the structure of Homebridge RPi quite well, there’s a lot of places where a new sensor type needs to be added, but at least it’s pretty straightforward.

I’m bitching a bit about naming and keeping the code sorted, but overall it looks OK.

2022-11-26 08:58 UTC, ebaauw commented on config.schema.json
> +                          "carbon"
Please use `co` or `carbonmonoxide` your distinguish from potential future CO2 sensors.

2022-11-26 08:58 UTC, ebaauw commented on config.schema.json
> +                          "carbon"
Please keep the alphabetical sort order by type.  Also in the other lists and descriptions.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiAccessory/index.js
> +  async addCarbon (device) {
Please call this `addCarbonMonoxide()` to leave room for future CO2 sensors.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiPlatform.js
> +            case 'carbon':
Please keep sort order.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiService/GpioInput/GpioCarbon.js
> +class GpioCarbon extends GpioInput {
Please call this `GpioCarbonMonoxide`.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiService/GpioInput/index.js
> +  static get GpioCarbon () { return require('./GpioCarbon') }
Please maintain the sort order.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiService/index.js
> +  static get CarbonSensor () { return require('./RpiCarbonSensor') }
You don’t need this - these are services in the accessory for the Raspberry Pi.

2022-11-26 08:58 UTC, ebaauw commented on lib/RpiService/index.js
> +  static get GpioCarbon () { return require('./GpioInput').GpioCarbon }
Please maintain the sort order.

2022-11-26 08:58 UTC, ebaauw commented on package.json
> +    "url": "git+https://github.com/wjsroot/homebridge-rpi.git"
You would need this only if you want to publish an `npm` package under your own name.  In that case, you would have to change the package name as well, e.g. to `@wjsroot/homebridge-rpi`, as the `npm` repository requires package names to be unique.

2022-11-26 16:54 UTC, wjsroot commented
I greatly appreciate your help and feedback. Please let me know how this looks, I think I've gotten everything. I changed 'carbon' to 'carbonmonoxide'; this makes a lot of sense, I even have sensors that detect carbon dioxide, smart to add clarity.

2022-11-27 10:52 UTC, ebaauw approved these changes

2022-11-27 10:52 UTC, merged

2022-11-27 11:28 UTC, ebaauw commented
In v1.6.4.